using System.IO;
using UnrealBuildTool;

/// <summary>
/// The Rust simulation, as far as Unreal Build Tool is concerned.
///
/// ModuleType.External means "there is no C++ here to compile; here is a header and a
/// binary". Everything this file does is point at artefacts cargo produced:
///
///   rust/crates/blindside-ffi/include/blindside_sim.h   generated by cbindgen
///   rust/target/release/blindside_ffi.dll               the cdylib
///
/// It deliberately does NOT add blindside_ffi.dll.lib to PublicAdditionalLibraries. The
/// game module resolves the exports at runtime with GetProcAddress instead, which costs
/// about thirty lines of C++ and buys the ability to rebuild the Rust and reload it
/// without restarting the editor. See NOTES.md, "Hot reload".
///
/// No CRT setting is needed. A cdylib is a self-contained DLL that links its own copy of
/// the UCRT; nothing about Unreal's /MD, its allocator or its exception model reaches
/// across a C ABI. That is a real advantage of the DLL over the staticlib, which does
/// have to agree with Unreal about the CRT -- again, NOTES.md.
/// </summary>
public class BlindsideSim : ModuleRules
{
	public BlindsideSim(ReadOnlyTargetRules Target) : base(Target)
	{
		Type = ModuleType.External;

		// spikes/unreal/ffi/unreal/BlindsideFfi/Source/BlindsideSim -> spikes/unreal/ffi
		string SpikeRoot = Path.GetFullPath(Path.Combine(ModuleDirectory, "..", "..", "..", ".."));
		string RustRoot = Path.Combine(SpikeRoot, "rust");
		string IncludeDir = Path.Combine(RustRoot, "crates", "blindside-ffi", "include");
		string ArtifactDir = Path.Combine(RustRoot, "target", "release");
		string Dll = Path.Combine(ArtifactDir, "blindside_ffi.dll");

		if (Target.Platform != UnrealTargetPlatform.Win64)
		{
			// The spike is Win64 only. Saying so loudly beats failing later with a
			// missing-symbol error that looks like something else.
			throw new BuildException(
				"BlindsideSim: this spike has only been built for Win64. See NOTES.md, "
				+ "\"What breaks on other platforms\".");
		}

		if (!File.Exists(Path.Combine(IncludeDir, "blindside_sim.h")) || !File.Exists(Dll))
		{
			// The Rust must be built first. Failing here with the command to run is worth
			// more than a compiler error about a header that is not there.
			throw new BuildException(
				"BlindsideSim: the Rust artefacts are missing. Run\n"
				+ "    cargo build -p blindside-ffi --release\n"
				+ "in " + RustRoot + ", or just run spikes/unreal/ffi/build.ps1, which does\n"
				+ "both halves in order.");
		}

		// PublicSystemIncludePaths, not PublicIncludePaths: the generated header is not
		// ours to keep warning-clean under Unreal's warning level, and it is generated, so
		// a warning in it is not something a human would fix anyway.
		PublicSystemIncludePaths.Add(IncludeDir);

		// Where the DLL lives during development. The game module falls back to this when
		// there is no copy beside the executable, which is the in-editor case.
		PublicDefinitions.Add("BLINDSIDE_RUST_DLL_DIR=\"" + ArtifactDir.Replace("\\", "/") + "\"");

		// For a packaged build: stage the DLL beside the executable.
		RuntimeDependencies.Add("$(BinaryOutputDir)/blindside_ffi.dll", Dll);
	}
}
