/* GENERATED BY cbindgen FROM crates/blindside-ffi/src/lib.rs -- DO NOT EDIT.
 *
 * Regenerate with `cargo build -p blindside-ffi` (build.rs runs cbindgen).
 *
 * This file is the ENTIRE surface between the deterministic Rust simulation and any
 * engine client. Read it top to bottom and you have read the boundary.
 *
 * Note what is not here: there is no function that returns a world, a cave, an agent's
 * true position, or anything else an agent's policy is not allowed to know.
 * `blindside_sim::World` is `pub(crate)` in Rust, so the crate that generates this header
 * cannot name the type, let alone return it. That is the project's one invariant
 * (CLAUDE.md) expressed as an absence, and an absence is not something a future
 * "just for debugging" accessor can quietly work around: it would have to widen the sim's
 * own module privacy first, in a different crate, in a separate commit.
 */


#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Version of the *function* ABI: the names, signatures and calling convention. Bumped
 * when an existing function changes shape. A client that links a mismatched library
 * should refuse to run rather than call into it.
 */
#define BS_ABI_VERSION 1

/**
 * Version of the *belief snapshot* byte layout, independent of the function ABI, since
 * the snapshot will change far more often than the calls that carry it. Written into
 * every snapshot header so a stale renderer detects it rather than misreads the bytes.
 */
#define BS_BELIEF_SCHEMA 1

/**
 * Every call returns one of these. 0 is success and every failure is negative, so
 * `if (status < 0)` is a correct check in C for the whole API, forever.
 */
enum BsStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    BS_STATUS_OK = 0,
    /**
     * A `BsSim*` argument was null.
     */
    BS_STATUS_NULL_HANDLE = -1,
    /**
     * An out-parameter pointer was null.
     */
    BS_STATUS_NULL_OUT = -2,
    /**
     * The caller's buffer is smaller than `bs_sim_belief_bytes` reported.
     */
    BS_STATUS_BUFFER_TOO_SMALL = -3,
    /**
     * `agent_index` is not a live agent.
     */
    BS_STATUS_BAD_AGENT = -4,
    /**
     * An argument was outside its documented range.
     */
    BS_STATUS_BAD_ARGUMENT = -5,
    /**
     * A panic was caught at the boundary. The sim instance should be considered
     * poisoned: destroy it and make a new one. Reaching this is a bug in the sim, not in
     * the caller.
     */
    BS_STATUS_PANIC = -6,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum BsStatus BsStatus;
#else
typedef int32_t BsStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Opaque handle to one simulation. The C side only ever holds a pointer to this; the
 * layout is deliberately absent from the header, so a client cannot reach past the API
 * by casting. cbindgen emits it as an opaque struct because it is not `#[repr(C)]`.
 */
typedef struct BsSim BsSim;

/**
 * Fixed-size header of a belief snapshot. The caller's buffer holds one of these
 * followed immediately by `point_count` [`BsBeliefPoint`]s, with no padding between them
 * (`BsBeliefHeader` is 8-aligned and 72 bytes, `BsBeliefPoint` is 4-aligned and 16).
 *
 * Every fixed-point field is the RAW BITS of the sim's `Fx = fixed::types::I32F32`, as
 * `int64_t`. It is never converted to a float on the sim side -- DETERMINISM.md rule 1
 * forbids `f32`/`f64` anywhere in the sim, and that includes "just to hand to the
 * renderer". The renderer divides by 2^32 itself, on its own side of the line, where
 * floats are allowed and are nobody's determinism problem.
 */
typedef struct BsBeliefHeader {
    /**
     * [`BS_BELIEF_SCHEMA`] at the time the snapshot was written.
     */
    uint32_t schema;
    uint32_t agent_index;
    /**
     * The tick this belief is as of.
     */
    uint64_t tick;
    /**
     * Estimated pose. `Fx` raw bits; divide by 2^32 for metres.
     */
    int64_t pose_x;
    int64_t pose_y;
    int64_t pose_z;
    /**
     * Estimated heading. `Fx` raw bits; radians.
     */
    int64_t pose_yaw;
    /**
     * Trace of the position covariance -- how lost the agent thinks it is. `Fx` raw bits.
     * This is what makes drift legible in the point cloud.
     */
    int64_t pose_var;
    /**
     * Ticks since the last position fix. The "am I lost" readout.
     */
    uint32_t ticks_since_fix;
    /**
     * Number of `BsBeliefPoint`s following this header.
     */
    uint32_t point_count;
    /**
     * Reserved; currently always 0. Present so a flag can be added without moving fields.
     */
    uint32_t flags;
    /**
     * Explicit tail padding, so the struct's size is the same on every compiler and a
     * `memcmp` of two snapshots does not read uninitialised bytes.
     */
    uint32_t reserved;
} BsBeliefHeader;

/**
 * One accumulated sensor return in the agent's *estimated* frame.
 *
 * Coordinates are `Fx16.16` raw bits (`int32_t`), not the sim's full I32F32. A display
 * point does not need 32 fractional bits, and halving the width halves the per-frame
 * copy, which is the one cost that recurs forever. The sim keeps full precision; the
 * truncation happens here, on the render side of the line, and never feeds back.
 */
typedef struct BsBeliefPoint {
    int32_t x;
    int32_t y;
    int32_t z;
    /**
     * Return quality, 0..=65535. Drives point brightness.
     */
    uint16_t quality;
    /**
     * Ticks since this return was accumulated, saturating. Drives fade-out.
     */
    uint16_t age;
} BsBeliefPoint;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * A human-readable name for a status. The returned pointer is to a `'static`
 * NUL-terminated string in the library's read-only data. **The caller must not free it**;
 * it stays valid for as long as the library is loaded.
 */
const char *bs_status_message(BsStatus status);

/**
 * [`BS_ABI_VERSION`] of the loaded library. Call this first and refuse to continue on a
 * mismatch; it is the one call whose signature is promised never to change.
 */
uint32_t bs_abi_version(void);

/**
 * [`BS_BELIEF_SCHEMA`] of the loaded library.
 */
uint32_t bs_belief_schema(void);

/**
 * Size in bytes of [`BsBeliefHeader`] as this library laid it out. A client compares it
 * with its own `sizeof` at startup; a mismatch means the header and the binary disagree
 * and every snapshot after that would be read at the wrong offsets.
 */
uint32_t bs_belief_header_size(void);

/**
 * Size in bytes of [`BsBeliefPoint`]. See [`bs_belief_header_size`].
 */
uint32_t bs_belief_point_size(void);

/**
 * Create a simulation for `seed`.
 *
 * `belief_points` is the stand-in point-cloud size per agent; pass 0 for the default
 * (8192). It exists so the spike's benchmark can sweep sizes without a rebuild, and it
 * disappears in Phase 3, when the count comes from the agent's actual belief.
 *
 * Returns null if `belief_points` exceeds the ceiling, or on allocation failure. The
 * returned pointer must be given to [`bs_sim_destroy`] exactly once.
 */
struct BsSim *bs_sim_create(uint64_t seed, uint32_t belief_points);

/**
 * Destroy a simulation. Null is a no-op, so a client's teardown path needs no null
 * check. Passing the same pointer twice is undefined, as it is for `free`.
 *
 * # Safety
 * `sim` must be null, or a pointer returned by [`bs_sim_create`] and not yet destroyed.
 */
void bs_sim_destroy(struct BsSim *sim);

/**
 * Advance the sim by `ticks` ticks and refresh agent 0's staged belief.
 *
 * This is the whole of "run the simulation". A client with a fixed timestep calls it
 * with 1 per sim tick; a client catching up after a hitch calls it with n.
 *
 * # Safety
 * `sim` must be a live pointer from [`bs_sim_create`], and no other thread may be
 * calling into the same handle concurrently.
 */
BsStatus bs_sim_step(struct BsSim *sim, uint32_t ticks);

/**
 * Write the current tick to `out_tick`.
 *
 * # Safety
 * `sim` must be live; `out_tick` must point to a writable `uint64_t`.
 */
BsStatus bs_sim_tick(const struct BsSim *sim, uint64_t *out_tick);

/**
 * Write the seed this sim was created with to `out_seed`.
 *
 * # Safety
 * As [`bs_sim_tick`].
 */
BsStatus bs_sim_seed(const struct BsSim *sim, uint64_t *out_seed);

/**
 * Copy the 32-byte BLAKE3 state hash into `out32`.
 *
 * This is the number the desync canary compares. A client that shows it on screen is
 * showing the same value the server and the harness compute for that tick, which makes
 * "the two machines disagree" something a human can see rather than infer.
 *
 * # Safety
 * `sim` must be live; `out32` must point to at least 32 writable bytes.
 */
BsStatus bs_sim_state_hash(const struct BsSim *sim, uint8_t *out32);

/**
 * Number of agents whose belief can be snapshotted.
 *
 * STAND-IN, see [`BS_STANDIN_AGENT_COUNT`]: this crate cannot ask the sim, because the
 * roster lives in `World`, which is `pub(crate)`.
 *
 * # Safety
 * As [`bs_sim_tick`].
 */
BsStatus bs_sim_agent_count(const struct BsSim *sim, uint32_t *out_count);

/**
 * Bytes [`bs_sim_belief_snapshot`] will write for `agent_index`. Call it once at startup
 * and size the buffer; never call it on the hot path, because the size is fixed for the
 * life of the sim.
 *
 * # Safety
 * `sim` must be live; `out_bytes` must point to a writable `uint32_t`.
 */
BsStatus bs_sim_belief_bytes(const struct BsSim *sim,
                             uint32_t agent_index,
                             uint32_t *out_bytes);

/**
 * Copy `agent_index`'s belief into the caller's buffer: a [`BsBeliefHeader`] followed by
 * `header.point_count` [`BsBeliefPoint`]s.
 *
 * The buffer belongs to the caller from creation to destruction. Nothing is allocated
 * here, nothing is handed back to free, and the library keeps no pointer into it after
 * the call returns. This is the call that happens every frame forever, so it is a bounds
 * check and two memcpys and nothing else.
 *
 * Fails with [`BsStatus::BufferTooSmall`] rather than writing a partial snapshot, so a
 * caller that sized its buffer against an older schema gets an error, not silent garbage.
 *
 * # Safety
 * `sim` must be live. `buffer` must point to at least `buffer_bytes` writable bytes.
 * `out_written` may be null.
 */
BsStatus bs_sim_belief_snapshot(const struct BsSim *sim,
                                uint32_t agent_index,
                                uint8_t *buffer,
                                uint32_t buffer_bytes,
                                uint32_t *out_written);

/**
 * Deliberately panic inside the library, to prove the boundary catches it.
 *
 * SPIKE ONLY. It exists so NOTES.md can *show* a caught panic returning
 * [`BsStatus::Panic`] with the editor still running, rather than assert that it would.
 * It must not exist in a shipped library; `tests/header_surface.rs` names it as the one
 * allowed exception, so deleting it does not mean editing the test twice.
 *
 * # Safety
 * `sim` must be live.
 */
BsStatus bs_sim_spike_force_panic(const struct BsSim *sim);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
